test 23

diff --git a/.github/workflows/detox-e2e-tests.yml b/.github/workflows/detox-e2e-tests.yml
--- a/.github/workflows/detox-e2e-tests.yml
+++ b/.github/workflows/detox-e2e-tests.yml
@@ -223,6 +223,129 @@
 
 # LATEST TEST
 
+# name: Run Detox Tests
+# on:
+#   push:
+#     branches: [main, master, testBranch]
+#   pull_request:
+#     branches: [master, main, testBranch]
+
+# jobs:
+#   find-test-files:
+#     name: Find Detox test files
+#     runs-on: macos-latest
+#     outputs:
+#       test-files: ${{ steps.set-test-files.outputs.test-files }}
+#     steps:
+#       - name: Checkout Code
+#         uses: actions/checkout@v4
+
+# - name: Find test files
+#   id: set-test-files
+#   run: |
+#     TEST_FILES=$(find e2e -name '*.test.js' | sed 's|e2e/||g' | jq -R -s -c 'split("\n")[:-1]')
+#     echo "list of files"
+#     echo "test-files=$TEST_FILES" >> $GITHUB_OUTPUT
+
+#       - name: Debug test-files output
+#         run: |
+#           echo "Output test-files: ${{ steps.set-test-files.outputs.test-files }}"
+
+# - name: Validate test files
+#   run: |
+#     if [ "${{ steps.set-test-files.outputs.test-files }}" == "[]" ]; then
+#       echo "No test files found. Exiting."
+#       exit 1
+#     fi
+#   build-ios:
+#     name: iOS - Build app for Detox tests
+#     runs-on: macos-latest
+
+#     steps:
+#       - name: Checkout Code
+#         uses: actions/checkout@v4
+#         with:
+#           fetch-depth: 1
+
+#       - name: Setup Node.js
+#         uses: actions/setup-node@v4
+#         with:
+#           node-version: 22.2.0
+
+#       - name: Install node_modules
+#         run: npm install
+
+#       - uses: actions/cache@v4
+#         id: cache
+#         with:
+#           path: ios/Pods
+#           key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
+
+#       - name: Pod Install
+#         run: cd ios && pod install
+
+#       # - name: Generate main.jsbundle
+#       #   run: npm run build:ios
+
+#       # - name: Build Detox
+#       #   run: npm run test:build
+
+#       - name: Upload iOS app
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: ios-app-artifact
+#           path: ios/build/Build/Products/Release-iphonesimulator/myapp.app
+#           retention-days: 1
+
+#   run-ios-detox-tests:
+#     needs: [build-ios, find-test-files]
+#     name: iOS - Run Detox tests
+#     runs-on: macos-latest
+
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         test-file: ${{ fromJson(needs.find-test-files.outputs.test-files) }}
+
+#     steps:
+#       - name: Checkout Code
+#         uses: actions/checkout@v4
+#         with:
+#           fetch-depth: 1
+
+#       - name: Download iOS app
+#         uses: actions/download-artifact@v4
+#         with:
+#           name: ios-app-artifact
+#           path: ios/build/Build/Products/Release-iphonesimulator/myapp.app
+
+#       - name: Setup Node.js
+#         uses: actions/setup-node@v4
+#         with:
+#           node-version: 22.2.0
+
+#       - name: Install node_modules
+#         run: npm install
+
+#       - name: Install Applesimutils
+#         run: |
+#           brew tap wix/brew
+#           brew install applesimutils
+#           echo applesimutils --list
+#       - name: Start Metro Server
+#         run: npm run detox:start &
+
+#       - name: Run Detox tests
+#         run: npm run test:e2e -- ${{ matrix.test-file }}
+
+#       - name: Upload Test Artifact - GitHub Action
+#         if: failure()
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: detox-ios-artifacts-${{ matrix.test-file }}
+#           path: artifacts
+#           retention-days: 1
+
 name: Run Detox Tests
 on:
   push:
@@ -240,23 +363,23 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
-- name: Find test files
-  id: set-test-files
-  run: |
-    TEST_FILES=$(find e2e -name '*.test.js' | sed 's|e2e/||g' | jq -R -s -c 'split("\n")[:-1]')
-    echo "list of files"
-    echo "test-files=$TEST_FILES" >> $GITHUB_OUTPUT
+      - name: Find test files
+        id: set-test-files
+        run: |
+          TEST_FILES=$(find e2e -name '*.test.js' | sed 's|e2e/||g' | jq -R -s -c 'split("\n")[:-1]')
+          echo "list of files"
+          echo "test-files=$TEST_FILES" >> $GITHUB_OUTPUT
 
       - name: Debug test-files output
         run: |
           echo "Output test-files: ${{ steps.set-test-files.outputs.test-files }}"
 
-- name: Validate test files
-  run: |
-    if [ "${{ steps.set-test-files.outputs.test-files }}" == "[]" ]; then
-      echo "No test files found. Exiting."
-      exit 1
-    fi
+      - name: Validate test files
+        run: |
+          if [ "${{ steps.set-test-files.outputs.test-files }}" == "[]" ]; then
+            echo "No test files found. Exiting."
+            exit 1
+          fi
   build-ios:
     name: iOS - Build app for Detox tests
     runs-on: macos-latest
@@ -345,4 +468,3 @@ jobs:
           name: detox-ios-artifacts-${{ matrix.test-file }}
           path: artifacts
           retention-days: 1
-
